### ISSUE TITLE
Request feedback on notes

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-redux#15]
As soon as initial notes are ready we need to request initial feedback...

**Comment by nelsonic** [comment]
[![contributions welcome](https://img.shields.io/badge/pr-welcome-brightgreen.svg?style=flat)](https://github.com/nelsonic/learn-redux/issues)

**Comment by nelsonic** [comment]
Got recommended image dimensions for tweet from: https://blog.bufferapp.com/ideal-image-sizes-social-media-posts

![learn-redux-header-twitter](https://cloud.githubusercontent.com/assets/194400/12328937/b87b2002-bad5-11e5-87eb-81ecab821dab.png)

@iteles you can _definitely_ do a _better_ Social post image... feel free to if you have time.
There will be another chance to tweet about this once we have our demo app ready...

**Comment by iteles** [comment]
Social media advice is that you should tweet the same content a few times at different times of day, so I'll use the updated photo for that (I didn't see this earlier, sorry). We'll also be making updates in the coming weeks so there'll be plenty of opportunity to tweet about it (using the #reactjs keyword) and try different ways of doing so :+1: (e.g. asking for feedback rather than announcing)

**Comment by nelsonic** [comment]
Enough people have found this repo useful. if anyone has any feedback they are welcome to share it. everyone else: https://github.com/dwyl/learn-elm/
